name: CI/CD Pipeline

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Build application
      run: npm run build
    - name: Build Docker image
      run: docker build -t ${{ secrets.REGISTRY_URL }}/greentech .
    - name: Push Docker image
      run: |
        docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY_URL }}
        docker push ${{ secrets.REGISTRY_URL }}/greentech

test:
  stage: test
  script:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test

deploy:
  stage: deploy
  script:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Deploy application
      run: npm run deploy
