name: Mirror and run GitLab CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Mirror + trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "https://gitlab.com//imranb25//greentech"
        env:
          FOLLOW_TAGS: "false"
          FORCE_PUSH: "false"
          GITLAB_HOSTNAME: "gitlab.com"
          GITLAB_USERNAME: "imranb25"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: "46364853"
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

  mirror_and_trigger:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      
      - name: Mirror changes to GitLab
        run: |
          # Use your custom script or tool to mirror changes to GitLab
          # This can involve pushing changes, syncing repositories, or using a third-party tool
          # Modify the command to match your specific mirroring requirements

      - name: Trigger GitLab pipeline
        run: |
          curl --request POST \
            --header 'Content-Type: application/json' \
            --header 'PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}' \
            --data '{}' \
            https://gitlab.com/api/v4/projects/45846472/trigger/pipeline
